// The 15 risk-first live runs, driven through the app's OWN request builder and
// provider — not a reimplementation of them.
//
// WHY NOT THE BROWSER. `qa/liveVerify.cjs` drives the real UI, which is the
// better test and is still the right tool wherever it can run. It cannot run
// here: this sandbox reaches the API from Node (curl and fetch both return 200)
// but the egress proxy resets the browser's TLS tunnels — `ERR_CONNECTION_RESET`
// on every https request Chromium makes, matching the `ws_closed_mid_exchange`
// entries the proxy's own status page reports. Two runs were spent establishing
// that, and neither reached Google, so neither was billed.
//
// What is lost by dropping the DOM is the button wiring, and that is the one
// layer already covered exhaustively — 385 mocked end-to-end checks drive every
// screen. What is NOT lost is the thing worth paying for: `buildFeatureRequest`,
// each tool's own `buildPrompt` and `toOptions`, the real aspect-ratio pinning,
// and the real provider. Those build the request byte for byte as the app does.

import { execFile, execFileSync } from 'node:child_process';
import os from 'node:os';
import { promisify } from 'node:util';
import fs from 'node:fs';
import path from 'node:path';
import { ALL_FEATURES, buildFeatureRequest, featureDef } from '../src/features/registry';
import type { FeatureKind } from '../src/types';
import { setGeminiConfig } from '../src/providers/runtimeConfig';
import { getActiveProvider } from '../src/providers';
import { jobsFor } from '../src/providers/shared';
import type { GenerateOptions } from '../src/providers/options';

// Bundled to a temp file before running (esbuild → CJS), so `__dirname` points
// at the bundle, not the repo. Run from the repo root.
const ROOT = process.cwd();
const execFileAsync = promisify(execFile);
const EXAMPLES = path.join(ROOT, 'public', 'examples');
const OUT = path.join(ROOT, 'qa', 'live-results');
// Generated by qa/makeMarker.cjs — the red-rectangle fixture the marker test
// needs. `burnMarker` is browser-only (canvas), so it is reproduced headlessly.
const MARKED_ROOM = path.join(OUT, 'fixture-room-marked.png');
// The street render with the brick neighbour's ground floor boxed, burned by
// the app's own burnMarker: node qa/canvasOps.cjs burn public/examples/
// ex-urban-context.jpg 0.005,0.545,0.21,0.2 qa/live-results/fixture-street-marked.png
const MARKED_STREET = path.join(OUT, 'fixture-street-marked.png');
// Inputs taken from the paid guide. TEST-ONLY: git-ignored, never published as
// an example (the repo is public). `guide:<file>` in a run resolves here; see
// qa/fixtures/README.md for which use case each file comes from.
const GUIDE = path.join(ROOT, 'qa', 'fixtures', 'guide');

interface Run {
  id: string;
  tool: FeatureKind;
  title: string;
  /** A file in public/examples/, `guide:<file>` for a test-only guide fixture,
   *  or an absolute path for a generated fixture. */
  input: string | null;
  /** Sent as `hasMarker` to buildPrompt — the input must ALREADY carry the box. */
  marked?: boolean;
  /** A tool's own second image (`extraInputs`), sent positionally after the input. */
  extra?: string;
  /** Settings overrides — the non-default variant, when that IS the risk. */
  settings?: Record<string, unknown>;
  /** The input is the output of an EARLIER run in the same set (a chained
   *  two-step tool). A dry run cannot read it yet and uses a placeholder. */
  chained?: boolean;
  /** Request-option overrides a tool's own `toOptions` does not set yet. */
  options?: Partial<GenerateOptions>;
  verdicts: string[];
}

const RUNS: Run[] = [
  {
    id: '01', tool: 'massing', input: null,
    title: 'Does text-only generation work on an image-editing model at all?',
    verdicts: ['PASS — a white massing model matching the typed brief', 'FAIL — no image, or an image unrelated to the brief'],
    settings: {
      brief: 'A 40-unit residential block with ground-floor retail around a courtyard',
      siteSize: '45m x 60m corner plot',
      context: 'Four-storey terraces on two sides, a park to the south',
    },
  },
  {
    id: '02', tool: 'multiView', input: 'elev-rendered.jpg',
    title: 'Six panels of one building. Do they agree with each other?',
    verdicts: ['PASS — every panel is the same building; storey count and window rhythm match', 'FAIL — panels disagree, or a single image came back'],
  },
  {
    id: '03', tool: 'cadElevation', input: 'elev-rendered.jpg', settings: { face: 'rear' },
    title: 'The rear face is not in the input. Reconstructed, or hallucinated?',
    verdicts: ['PASS — a flat orthographic rear elevation consistent with the front', 'FAIL — the front returned unchanged, or an unrelated building'],
  },
  {
    id: '04', tool: 'section', input: 'elev-rendered.jpg',
    title: 'Can a section be cut from one exterior view with no storey heights given?',
    verdicts: ['PASS — a cut section with a consistent floor rhythm and a poched cut line', 'FAIL — an elevation with no cut, or incoherent floors'],
  },
  {
    id: '05', tool: 'renderToPlan', input: 'elev-rendered.jpg',
    title: 'Running the pipeline BACKWARDS — does a usable plan come out?',
    verdicts: ['PASS — a top-down 2D plan whose footprint matches the massing', 'FAIL — a 3D/angled drawing, or a generic unrelated plan'],
  },
  {
    id: '06', tool: 'urbanContext', input: 'elev-rendered.jpg',
    title: 'Signage was asked for while stray text was forbidden. Does it stay clean?',
    verdicts: ['PASS — a street with neighbours and NO invented lettering', 'FAIL — shopfront signage or garbled text appears'],
  },
  {
    id: '07', tool: 'floorAnalysis', input: 'plan-input.jpg', settings: { layer: 'zoning' },
    title: 'The zoning layer demanded a keyed legend from outside the labels branch.',
    verdicts: ['PASS — coloured zones with a legend that matches them', 'FAIL — a legend naming zones that are not marked, or an obscured plan'],
  },
  {
    id: '08', tool: 'explodedAxon', input: 'elev-rendered.jpg', settings: { axis: 'layered' },
    title: 'Outward explodes diagonally; the prompt used to ask for VERTICAL guides.',
    verdicts: ['PASS — layers separated outward, guides following the explode direction', 'FAIL — vertical guides on a diagonal explode, or nothing exploded'],
  },
  {
    id: '09', tool: 'annotation', input: 'elev-rendered.jpg',
    title: 'The one tool that MUST write on the image. Is the text real words?',
    verdicts: ['PASS — arrows and legible, correctly spelled labels', 'FAIL — gibberish label-shapes, or no labels at all'],
  },
  {
    id: '10', tool: 'sketchPlan', input: 'sketch-input.jpg',
    title: 'Does a rough sketch become a CAD-style plan without inventing rooms?',
    verdicts: ['PASS — clean linework whose layout matches the sketch', 'FAIL — an invented plan, or the sketch barely changed'],
  },
  {
    id: '11', tool: 'sketchRender', input: 'sketch-input.jpg',
    title: "Does the render keep the sketch's masses, or replace them?",
    verdicts: ['PASS — same viewpoint and masses, resolved into a finished image', 'FAIL — a handsome building that is not the one drawn'],
  },
  {
    id: '12', tool: 'declutter', input: 'room-input.jpg',
    title: 'Does a strip-out keep the architecture and remove only the movable?',
    verdicts: ['PASS — same room, same windows and camera, emptied', 'FAIL — the shell changed, or furniture remains'],
  },
  {
    id: '13', tool: 'specSheet', input: 'room-input.jpg',
    title: 'A knolling flat-lay must not become a mood board — and it carries text.',
    verdicts: ["PASS — items from THIS room, flat on white, spelled correctly", 'FAIL — a collage of similar products, or gibberish labels'],
  },
  {
    id: '14', tool: 'facadeMaterial', input: 'elev-rendered.jpg',
    title: 'Does a material swap leave the geometry completely alone?',
    verdicts: ['PASS — identical building, different facade material', 'FAIL — geometry moved with the material, or nothing changed'],
  },
  {
    id: '15', tool: 'watercolour', input: 'elev-rendered.jpg',
    title: 'Does a stylised pass keep the building, or reinvent it?',
    verdicts: ['PASS — the same building, rendered as a watercolour', 'FAIL — a different building, or an unchanged photo'],
  },
];

/**
 * The second batch: SIX runs that verify the fixes made after the first fifteen,
 * plus the two questions the first fifteen never asked.
 *
 * Runs V1-V4 exist because a fix nobody re-ran is a guess. V3 and V4 are the
 * same clause (SHELL_CHECK) on two different tools: the evidence came from
 * Declutter, but the rewrite also lands on Stage/Restyle/Renovate, which share
 * that tail and have never been run against it.
 *
 * V5 is the question the plan called the biggest unknown from the start: does
 * the model read a burned-in red rectangle as an INSTRUCTION, or reproduce it as
 * part of the picture? Its input carries the box already.
 *
 * V6 is NOT a resolution test and must not be reported as one. `resolution`
 * reaches kie.ai only; Gemini has no equivalent parameter, so what is under test
 * here is the prompt's promise to resolve detail rather than invent it.
 */
const VERIFY: Run[] = [
  {
    id: 'V1', tool: 'urbanContext', input: 'elev-rendered.jpg',
    title: 'FIX CHECK — the signage boards are gone. Does the street stay unlettered?',
    verdicts: ['PASS — neighbours with blank fascias and no readable words anywhere', 'FAIL — any shopfront lettering, garbled or legible'],
  },
  {
    id: 'V2', tool: 'explodedAxon', input: 'elev-rendered.jpg', settings: { axis: 'layered' },
    title: 'FIX CHECK — roof form is now locked, and Outward forbids the vertical stack.',
    verdicts: ['PASS — flat overhanging roof preserved AND layers offset sideways', 'FAIL — a pitched roof, or layers stacked one directly above another'],
  },
  {
    id: 'V3', tool: 'declutter', input: 'room-input.jpg',
    title: 'FIX CHECK — the camera is now audited FIRST. Does the viewpoint hold?',
    verdicts: ['PASS — same camera, same window, same panes, room emptied', 'FAIL — the view shifts, or the window changes size or pane count'],
  },
  {
    id: 'V4', tool: 'interior', input: 'room-empty.jpg', settings: { mode: 'stage' },
    title: 'BLAST-RADIUS CHECK — Stage inherited the camera rewrite on another tool’s evidence.',
    verdicts: ['PASS — furnished from the identical camera, shell untouched', 'FAIL — the camera moves, or the rewrite has broken staging'],
  },
  {
    id: 'V5', tool: 'targetedSwap', input: MARKED_ROOM, marked: true,
    settings: { element: 'the beige fabric sofa inside the red rectangle', replacement: 'a dark green velvet three-seater sofa' },
    title: 'THE RED BOX. Instruction, or something to faithfully redraw?',
    verdicts: [
      'PASS — the sofa is swapped and NO red rectangle appears in the output',
      'FAIL — the red box is reproduced in the output, or the edit is ignored, or something outside the box changed',
    ],
  },
  {
    id: 'V6', tool: 'upscale', input: 'elev-line.jpg',
    title: 'Does an upscale resolve detail, or hallucinate detail that was never there?',
    verdicts: ['PASS — the same drawing, cleaner, with nothing added', 'FAIL — invented linework, or a redesigned drawing'],
  },
  // V7 is V6 again, after the medium lock. Kept as a SEPARATE id rather than a
  // re-run of V6 so the failing image stays on disk next to the fixed one —
  // a before and after is the only honest way to show a prompt fix worked.
  {
    id: 'V7', tool: 'upscale', input: 'elev-line.jpg',
    title: 'FIX CHECK — the medium lock. Does a line drawing stay a line drawing?',
    verdicts: [
      'PASS — line art on white, no sky, no lawn, no materials, no lighting',
      'FAIL — any render, sky, ground, colour or material the input did not have',
    ],
  },
];

/**
 * Round 3: the tools round 1 deliberately skipped.
 *
 * Each was skipped because it repeats a prompt shape an earlier run exercised.
 * That reasoning is only worth as much as the evidence behind it, so these run
 * the NON-DEFAULT, riskiest setting of each — the variant most likely to break
 * the lock, not the one most likely to look fine.
 *
 * Bird's Eye is NOT here and is not skipped: `inputKind: ['map']` and its own
 * hint reads "a top-down satellite or Maps screenshot". It is blocked on the
 * satellite fixture, like Place Object and Wireframe to Render. Running it on a
 * floor plan would test nothing and still cost money. I had previously listed it
 * as testable, from memory, without reading its inputKind.
 */
const SKIPPED: Run[] = [
  {
    id: 'W1', tool: 'atmosphere', input: 'elev-rendered.jpg',
    settings: { lighting: 'night', season: 'winter', mood: 'dramatic', keepPeople: true },
    title: 'Night AND winter AND dramatic — the largest change this tool can make at once.',
    verdicts: [
      'PASS — same building, same camera, relit for night; windows lit from within, winter ground',
      'FAIL — geometry or camera moves, or the light is unchanged',
    ],
  },
  {
    id: 'W2', tool: 'humanScale', input: 'elev-rendered.jpg',
    settings: { density: 'busy', setting: 'commercial', vehicles: true, planting: true },
    title: 'Busy, with vehicles and planting. Are the figures the right SIZE, and are they ignoring us?',
    verdicts: [
      'PASS — figures scale correctly against the door, nobody posing at the camera, building untouched',
      'FAIL — giant or doll-sized people, faces to camera, or the building altered to fit them',
    ],
  },
  {
    id: 'W3', tool: 'reflection', input: 'elev-rendered.jpg',
    settings: { mode: 'mirror', reflect: '' },
    title: 'Mirror glazing. Does the reflection break at the mullions, or dissolve the frames?',
    verdicts: [
      'PASS — every frame and mullion still in place, reflection interrupted by each one',
      'FAIL — one continuous mirror sheet across the frames, or frames gone',
    ],
  },
  {
    id: 'W4', tool: 'renderRefine', input: 'elev-rendered.jpg',
    settings: { level: 'finish', fixPeople: true, fixMaterials: true },
    title: 'The strongest refinement level on an already-clean render. Does it redesign?',
    verdicts: [
      'PASS — the same building, better executed; nothing added, moved or restyled',
      'FAIL — a more interesting building than the one submitted',
    ],
  },
  // W6 is W1 again, after the roof clause was promoted into the shared lock.
  // Separate id so the failing night render stays beside the fixed one.
  {
    id: 'W6', tool: 'atmosphere', input: 'elev-rendered.jpg',
    settings: { lighting: 'night', season: 'winter', mood: 'dramatic', keepPeople: true },
    title: 'FIX CHECK — the roof clause is now in the lock all seven visualization tools share.',
    verdicts: [
      'PASS — flat overhanging roof survives the relight; night and winter still applied',
      'FAIL — a pitched or hipped roof again, or the relight stopped working',
    ],
  },
  {
    id: 'W5', tool: 'programDiagram', input: 'elev-rendered.jpg',
    settings: { levels: 'Ground: garage and entry. First: living and kitchen. Second: bedrooms.', orientation: 'isometric' },
    title: 'Isometric, not the default. Does it use THIS building, or generic stacked slabs?',
    verdicts: [
      'PASS — this building separated by level, its own massing and openings legible',
      'FAIL — anonymous stacked boxes that could be any building',
    ],
  },
];

/**
 * Round 4: tools added after the verification rounds. Each needs one approved
 * paid run to earn its worked example; `registryLint` keeps them on
 * AWAITING_LIVE_RUN until that example exists.
 *
 * X1 is the hard case on purpose: the reference is a two-storey HOUSE and the
 * massing is a courtyard BLOCK, so a render that quietly built the reference
 * instead of the massing cannot hide.
 */
/**
 * Build plan, Phase 1. Inputs are our own wherever one exists, so a passing run
 * can become the published worked example directly.
 *
 * Y1 reads the moves from our own courtyard massing — close to the guide's own
 * example, so the moves are visible and the last panel can be judged.
 * Y2 is the bubble diagram qa/makeBubble.cjs draws, built so each adjacency
 * rule (touching, linked, apart) appears and can be checked.
 * Y3 closes the loop: Room → Moodboard (our board-boho) → Room.
 * Y4 uses the guide's terracotta jali photo (#59, test-only): the guide's own
 * #55 input is a finished building render, which cannot test "translate, do
 * not copy" — there is no object to copy.
 */
const NEW_TOOLS: Run[] = [
  // Phase 4 — the knowledge tools, all searched.
  {
    id: 'K1', tool: 'materialPoster', input: null, settings: { topic: 'Terracotta jali blocks' },
    title: 'A researched poster from a name alone. True bullets, no invented numbers?',
    verdicts: [
      'PASS — a bento poster: clay close-up, exploded block assembly, airflow section; plain true bullets; title spelled',
      'FAIL — fabricated U-values or percentages, panels about something else, or garbled text',
    ],
  },
  {
    id: 'K2', tool: 'materialPoster', input: 'guide:uc59-input1.jpg', settings: { topic: 'Terracotta jali blocks' },
    title: 'The same poster, with a photo of THE jali. Does the poster draw that pattern?',
    verdicts: [
      'PASS — the close-up and assembly show the photo’s colour and perforation pattern',
      'FAIL — a generic jali unlike the photo',
    ],
  },
  {
    id: 'K3', tool: 'architectTimeline', input: null,
    settings: { architect: 'Zaha Hadid', fromStyle: 'sharp deconstructivist angles', toStyle: 'fluid organic curves' },
    title: 'Six real buildings, real years, in order — and drawn as one family?',
    verdicts: [
      'PASS — real built works (e.g. Vitra Fire Station 1993 … Heydar Aliyev Centre 2012) in date order, names spelled, one drawing style',
      'FAIL — invented projects, wrong or out-of-order years, mixed styles, or a portrait of the architect',
    ],
  },
  {
    id: 'K4', tool: 'blueprintEvolution', input: null, settings: { typology: 'Gothic to contemporary church design' },
    title: 'Seven stages, flat to photo-real, each a different church in date order?',
    verdicts: [
      'PASS — blueprint sheet; stage 1 a drafted plan, stage 7 a photo-real modern church; style names and dates in order',
      'FAIL — one church repeated, dates out of order, or text soup',
    ],
  },
  {
    id: 'K5', tool: 'redPen', input: 'interior-stage.jpg',
    title: 'A constructive review of our staged room. Real flaws, room unchanged?',
    verdicts: [
      'PASS — 4-6 red circles on visible issues, short legible block-capital notes, the room underneath identical',
      'FAIL — the room redrawn, notes pointing at nothing, or illegible scrawl',
    ],
  },
  {
    id: 'K6', tool: 'redPen', input: 'interior-restyle.jpg', settings: { tone: 'roast' },
    title: 'The roast. Funny about the DESIGN — and still about real flaws?',
    verdicts: [
      'PASS — sarcastic one-liners about visible design choices, nothing about people, room unchanged',
      'FAIL — invented flaws, insults aimed at people, or the room altered',
    ],
  },
  // Phase 3b.
  {
    id: 'U1', tool: 'systemsCutaway', input: 'ex-human-scale.jpg',
    title: 'Our house cut open for sun and air. Same house, same camera, physics right?',
    verdicts: [
      'PASS — the house from the same camera, sliced; summer sun steeper than winter; cool air in low, hot air out high; labels spelled',
      'FAIL — a different house, warm air sinking, the sun angles reversed, or garbled labels',
    ],
  },
  {
    id: 'U2', tool: 'systemsCutaway', input: 'guide:uc51-input1.jpg', settings: { system: 'green' },
    title: 'A planted tower: soil, roots, irrigation, rainwater. Green and grey only?',
    verdicts: [
      'PASS — balconies cut to show substrate, roots and pipes; roof water to tanks to planting; green-and-grey palette',
      'FAIL — trees in pots on the outside only, water flowing nowhere, or a full-colour render',
    ],
  },
  {
    id: 'U3', tool: 'marketingBoard', input: 'ex-atmosphere.jpg',
    settings: { title: 'Hillside House', facts: 'Bengaluru, India · 320 m² · 2026' },
    title: 'A board for the night render. Typography that fits — and ONLY the facts we typed?',
    verdicts: [
      'PASS — the night render as hero, unchanged; “Hillside House”, Bengaluru, 320 m², 2026 and nothing else numeric; type suits the house',
      'FAIL — invented areas, awards or architects, the house redrawn, or misspelled text',
    ],
  },
  {
    id: 'U4', tool: 'magazine', input: 'interior-stage.jpg',
    title: 'A feature page about our staged living room. Real sentences, real crops?',
    verdicts: [
      'PASS — a 9:16 page led by this room, detail crops from it, readable English, no brands or prices',
      'FAIL — pseudo-text, a different room in the photos, or invented brands and prices',
    ],
  },
  // Phase 3a — all on our own images, so a pass can be published.
  {
    id: 'Q1', tool: 'phasing', input: 'ex-human-scale.jpg',
    title: 'Three stages, one camera. Do all three overlay the finished render?',
    verdicts: [
      'PASS — excavation, frame and envelope from the identical camera; the neighbours and horizon unmoved; the frame matching the house’s floor levels',
      'FAIL — the camera or crop moves between stages, the structure outgrows the house, or the street changes',
    ],
  },
  {
    id: 'Q2', tool: 'reframe', input: 'ex-human-scale.jpg',
    title: '16:9 to a 9:16 story. Sky above, street below — and the house untouched?',
    verdicts: [
      'PASS — a seamless 9:16 picture; sky and foreground continue the original’s light and perspective; no seam after paste-back',
      'FAIL — grey margins left, a visible seam, a mirrored repeat, or a second building above the house',
    ],
  },
  {
    id: 'Q3', tool: 'reframe', input: 'ex-massing.jpg', settings: { ratio: '21:9' },
    title: 'A 3:2 massing photo to a 21:9 banner. The table and backdrop continue sideways?',
    verdicts: [
      'PASS — the white model unchanged, the base and backdrop extended left and right as more of the same',
      'FAIL — new buildings invented beside the model, or the model stretched',
    ],
  },
  {
    id: 'Q4', tool: 'groundFloor', input: MARKED_STREET, marked: true,
    title: 'A café in the brick building’s ground floor. Only inside the box — and the box gone?',
    verdicts: [
      'PASS — a lit café frontage aligned to the bays above, people inside, everything outside the box unchanged, no red line',
      'FAIL — the upper floors or the house altered, the frontage ignoring the facade grid, or the red rectangle still there',
    ],
  },
  // Phase 2a — all on guide inputs (test-only).
  {
    id: 'Z1', tool: 'siteLinework', input: 'guide:uc32-input1.jpg',
    title: 'Satellite to linework. Does it OVERLAY the tile, with no text and no trees?',
    verdicts: [
      'PASS — black line on white matching the tile’s streets and footprints, clear weight hierarchy, no labels, no trees',
      'FAIL — straightened or invented streets, grey fills, labels, or trees left in',
    ],
  },
  {
    id: 'Z2', tool: 'siteAnalysis', input: 'guide:uc44-input1.jpg',
    title: 'The site in red, the sun on the south edge — and only street names that are really there?',
    verdicts: [
      'PASS — site where it was, sun arc along the bottom rising on the right, access arrows on real streets, labels readable in the input',
      'FAIL — invented street names, a moved site, the sun on the wrong edge, or Maps UI left in',
    ],
  },
  {
    id: 'Z3', tool: 'placeInSite', input: 'guide:uc46-input1.jpg', extra: 'guide:uc46-input2.jpg',
    title: 'THAT villa, on THAT plot, in the photo’s own light — and the rest of the photo untouched?',
    verdicts: [
      'PASS — the white villa on the outlined plot, scaled to the trees and houses, shadows agreeing, hillside unchanged, red line gone',
      'FAIL — a generic building, the photo re-rendered, a wrong scale, or the red outline still visible',
    ],
  },
  {
    id: 'Z4', tool: 'siteAnalysis3d', input: 'guide:uc56-input1.jpg',
    settings: { coords: '27.1751, 78.0421', wind: 'NW' },
    title: 'The coin, without a reference. Compass clockwise, sun leaning south, wind from where we SAID?',
    verdicts: [
      'PASS — a circular isometric base, white beyond it, N top-right then E S W clockwise, sun arc to the south, wind arrows from the north-west',
      'FAIL — the whole map uncropped, compass out of order, wind from elsewhere, or photoreal texture',
    ],
  },
  {
    id: 'Z5', tool: 'siteAnalysis3d', input: 'guide:uc56-input1.jpg', extra: 'guide:uc56-output1.jpg',
    settings: { coords: '27.1751, 78.0421', wind: 'none' },
    title: 'With the reference diagram. Does it copy the LOOK — and not the place?',
    verdicts: [
      'PASS — the reference’s graphic language on THIS site’s geography; no wind arrows (none set)',
      'FAIL — the reference’s own buildings reproduced, or wind arrows drawn anyway',
    ],
  },
  {
    id: 'Z6', tool: 'urbanLayers', input: 'guide:uc58-input1.jpg',
    title: 'Four layer maps of ONE circle. Do they stack?',
    verdicts: [
      'PASS — four circles of the same extent; roads in map 3 run between the buildings of map 1; four titles spelled',
      'FAIL — maps of different extents or places, buildings in the pink blocks map, or garbled titles',
    ],
  },
  {
    id: 'Z7', tool: 'urbanLayers', input: path.join(OUT, 'run-Z6-output.png'), chained: true, settings: { step: 'stack' },
    title: 'Step two, on step one’s own sheet. Are the discs the SAME maps?',
    verdicts: [
      'PASS — the four maps from Z6, stacked isometrically in order, dotted alignment lines, titles to the right',
      'FAIL — redrawn or different maps, shadows on the discs, or titles missing',
    ],
  },
  {
    id: 'Z8', tool: 'sitePhoto', input: null, settings: { coords: '38.8977° N, 77.0365° W' },
    title: 'The guide’s own coordinates — the White House. Is the landmark there because it IS there?',
    verdicts: [
      'PASS — a believable Washington street view near the White House; any landmark genuinely at that spot; signs unreadable; sources listed',
      'FAIL — a generic street, a different city, or readable invented signage',
    ],
  },
  {
    id: 'Z9', tool: 'sitePhoto', input: null, settings: { coords: '51.5246, -0.0787' },
    title: 'An ordinary street in Shoreditch. Local character without a landmark to lean on?',
    verdicts: [
      'PASS — London brick, Victorian warehouses and terraces, London street furniture; no famous landmark moved in',
      'FAIL — an anywhere-street, or the Shard/Big Ben dropped into an ordinary road',
    ],
  },
  {
    id: 'Z10', tool: 'siteHistory', input: null, settings: { coords: '27.1751, 78.0421', place: 'Taj Mahal complex' },
    title: 'A well-documented site. Same frame in every panel, real years in order?',
    verdicts: [
      'PASS — four plans of one frame, years increasing (c. 1632 onward), the last matching today, captions spelled',
      'FAIL — panels at different scales, invented events or dates, or garbled captions',
    ],
  },
  {
    id: 'Z11', tool: 'siteHistory', input: null, settings: { coords: '51.4818, -0.1446' },
    title: 'Battersea Power Station, unnamed. Does search find it — and does it stay honest?',
    verdicts: [
      'PASS — the power station recognised; build, closure and redevelopment in order with plausible years or circa dates',
      'FAIL — a different site, invented history, or dates out of order',
    ],
  },
  // Phase 1 retries, after the fixes — own ids so the partial runs stay beside them.
  {
    id: 'Y1b', tool: 'conceptDiagram', input: 'ex-massing.jpg',
    title: 'FIX CHECK — one row, and the last panel keeps the asymmetry?',
    verdicts: [
      'PASS — ONE row of 4 panels, same camera, ending on THIS massing with its uneven heights and steps; captions spelled',
      'FAIL — two rows again, a repeated panel, or a tidy symmetric ending',
    ],
  },
  {
    id: 'Y2b', tool: 'bubblePlan', input: 'bubble-input.jpg',
    title: 'FIX CHECK — the same plan, with no room names lettered in?',
    verdicts: [
      'PASS — the adjacencies of Y2 kept, and no text anywhere on the plan',
      'FAIL — room names or any other text on the plan, or the adjacencies lost',
    ],
  },
  {
    id: 'Y4b', tool: 'conceptBoard', input: 'guide:uc59-input1.jpg',
    title: 'FIX CHECK — no printed part names, and a pavilion that is more than a wall of blocks?',
    verdicts: [
      'PASS — three parts, title and short lines only (no CONCEPT / MAIN RENDER / SECTION labels); the jali’s light, rhythm and porosity carried into structure and space',
      'FAIL — part names printed again, or the pavilion still simply built out of jali blocks',
    ],
  },
  {
    id: 'Y1', tool: 'conceptDiagram', input: 'ex-massing.jpg',
    title: 'Moves read from the form. Same camera throughout, ending on THIS massing?',
    verdicts: [
      'PASS — 4 panels from one camera, one visible move each, the last matching the courtyard massing; captions spelled',
      'FAIL — panels from different angles, a final form that is not the input, or garbled captions',
    ],
  },
  {
    id: 'Y2', tool: 'bubblePlan', input: 'bubble-input.jpg',
    title: 'Bubbles to rooms. Do touching bubbles share doors — and do apart ones not?',
    verdicts: [
      'PASS — eight rooms in the diagram’s arrangement; hall opens to both bedrooms, bath and living; bedrooms do not connect; no handwriting left',
      'FAIL — a generic flat ignoring the bubbles, bedrooms opening into each other, or the title/note/N surviving',
    ],
  },
  {
    id: 'Y3', tool: 'moodboardSpace', input: 'board-boho.jpg',
    title: 'Our own mood board back into a room. A room — or another board?',
    verdicts: [
      'PASS — one living-room photograph in terracotta, linen, rattan and aged teak; no swatches, no text',
      'FAIL — a grid or collage, the board hung as art, or a generic neutral room',
    ],
  },
  {
    id: 'Y4', tool: 'conceptBoard', input: 'guide:uc59-input1.jpg',
    title: 'A perforated terracotta block as inspiration. Translated — or a building shaped like a block?',
    verdicts: [
      'PASS — three parts showing one pavilion that uses perforation, light and terracotta as a language; title spelled',
      'FAIL — a pavilion that is literally a jali block, the photo pasted on the board, or unrelated buildings per part',
    ],
  },
];

/**
 * Phase 0 of the build plan: the live runs OWED on tools already built.
 *
 * O1-O3 were blocked on fixtures (registryLint's NO_FIXTURE). The guide supplies
 * them now, for testing only. Bird's Eye runs on the guide's TOP-DOWN satellite
 * (#32), not its own example (#08): that one is an oblique photo from a plane
 * window, which is not the input this tool's hint asks for, so it would test
 * something the tool never promised.
 *
 * O2 runs the NEW interior branch, because the guide's wireframe (#09) is a
 * room. Running it through the exterior prompt (storeys, facade, roof) would
 * have paid to confirm a mismatch readable in the source.
 *
 * X1 is the hard case on purpose: the reference is a two-storey HOUSE and the
 * massing is a courtyard BLOCK, so a render that quietly built the reference
 * instead of the massing cannot hide.
 */
const OWED: Run[] = [
  {
    id: 'O1', tool: 'birdsEye', input: 'guide:uc32-input1.jpg',
    title: 'A flat satellite tile becomes an aerial view. Is it the SAME place?',
    verdicts: [
      'PASS — an oblique aerial of this street grid and these footprints, no map interface',
      'FAIL — a generic city, streets that are not in the tile, or labels and UI left in',
    ],
  },
  {
    id: 'O2', tool: 'wireframeRender', input: 'guide:uc09-input1.jpg', settings: { subject: 'interior' },
    title: 'INTERIOR branch. Does it furnish what is modelled — and only that?',
    verdicts: [
      'PASS — same room and camera; the modelled sofas, shelving, TV and plants, rendered; nothing added',
      'FAIL — added rugs, art or decor, moved or redesigned furniture, or a changed camera',
    ],
  },
  {
    id: 'O3', tool: 'placeObject', input: 'guide:uc25-input1.jpg', extra: 'guide:uc25-input2.jpg',
    settings: { kind: 'artwork', placement: 'add', target: '' },
    title: 'The artwork in the second image, hung in the room. THAT painting, at a real size?',
    verdicts: [
      'PASS — the same mountain painting, flat on a wall, believable size, room otherwise unchanged',
      'FAIL — a different painting, wrong perspective or scale, or the room altered',
    ],
  },
  {
    id: 'X1', tool: 'massingRender', input: 'ex-massing.jpg', extra: 'elev-rendered.jpg',
    title: 'Massing + a reference with a DIFFERENT form. Whose building comes back?',
    verdicts: [
      'PASS — the courtyard block, every volume and step intact, clad and lit like the reference',
      'FAIL — the reference house comes back, or the massing changed shape, or it is still a model on a table',
    ],
  },
  // Retries after the fixes, under their own ids so the failing images stay
  // beside the fixed ones. X1 dropped the aerial camera to street level, took
  // the reference's garage door, and came back in the REFERENCE's frame shape;
  // O3 placed the right painting but came back square from a portrait room.
  // Fixed by pinning a multi-image request to its FIRST image's ratio
  // (effectiveAspect) and by naming the camera and the doors in the prompt.
  {
    id: 'X1b', tool: 'massingRender', input: 'ex-massing.jpg', extra: 'elev-rendered.jpg',
    title: 'FIX CHECK — camera and doors named, frame pinned to the massing. Whose building now?',
    verdicts: [
      'PASS — the courtyard block from the same high angle, same 3:2 frame, clad and lit like the reference, no garage door',
      'FAIL — the camera drops again, the reference house’s doors return, or the frame is not 3:2',
    ],
  },
  // X1b kept the camera and the frame but split the courtyard block into
  // separate stepped buildings and cut windows into solid faces. Now: openings
  // default to solid, and "THE BLOCK DOES NOT SPLIT" is in the lock.
  {
    id: 'X1c', tool: 'massingRender', input: 'ex-massing.jpg', extra: 'elev-rendered.jpg',
    title: 'FIX CHECK — solid by default, the block named as one. One building now?',
    verdicts: [
      'PASS — one continuous courtyard block with its steps, high aerial camera, 3:2, solid faces clad like the reference',
      'FAIL — the block splits into separate buildings again, windows cut into faces, or the camera drops',
    ],
  },
  {
    id: 'O3b', tool: 'placeObject', input: 'guide:uc25-input1.jpg', extra: 'guide:uc25-input2.jpg',
    settings: { kind: 'artwork', placement: 'add', target: '' },
    title: 'FIX CHECK — the frame pinned to the room. Portrait in, portrait out?',
    verdicts: [
      'PASS — the same painting on the wall, the room in its own 9:16 portrait frame, camera unchanged',
      'FAIL — a square or landscape frame again, or a different painting',
    ],
  },
];

/**
 * Phase 0, G3: does the IMAGE model accept Google Search grounding at all?
 *
 * One call, through a text-only tool so nothing but the new field is under test.
 * The brief names a real, specific place, so a grounded answer has something to
 * look up; the report records any sources returned.
 */
const PROBE: Run[] = [
  {
    id: 'G1', tool: 'massing', input: null, options: { grounding: true },
    settings: {
      brief: 'A six-storey courtyard housing block on the empty corner plot, in the real context of this location',
      siteSize: 'about 40m x 50m',
      context: 'The streets around 51.5246° N, 0.0787° W in London — look up what is actually there',
    },
    title: 'GROUNDING PROBE — does the image model accept google_search and still return an image?',
    verdicts: [
      'PASS — an image comes back (sources listed if the engine reports them)',
      'FAIL — an HTTP error naming the tools field, or text instead of an image',
    ],
  },
];

/** A 1×1 PNG, standing in for a chained input a dry run has not produced yet. */
const PLACEHOLDER =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';

/**
 * fetch, via curl. Node's built-in fetch gives up waiting for response headers
 * after 300 s and cannot be told otherwise without the `undici` package — and
 * live run O1 (Bird's Eye) hit exactly that twice: the model was still working
 * when Node hung up. A browser has no such limit, so the harness should not
 * either. Same URL, same headers, same body; curl honours HTTPS_PROXY.
 *
 * The key travels in a 0600 header FILE, never on the command line, where any
 * process listing would show it.
 */
async function curlFetch(input: string | URL | Request, init?: RequestInit): Promise<Response> {
  const url = String(input instanceof Request ? input.url : input);
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'and-curl-'));
  const hdr = path.join(dir, 'h');
  const body = path.join(dir, 'b');
  try {
    const headers = new Headers(init?.headers);
    fs.writeFileSync(hdr, [...headers].map(([k, v]) => `${k}: ${v}`).join('\n'), { mode: 0o600 });
    const args = ['-sS', '--max-time', '900', '-X', init?.method ?? 'GET', '-H', `@${hdr}`, '-w', '\n%{http_code}', url];
    if (init?.body !== undefined && init.body !== null) {
      fs.writeFileSync(body, String(init.body), { mode: 0o600 });
      args.splice(args.length - 1, 0, '--data-binary', `@${body}`);
    }
    const { stdout } = await execFileAsync('curl', args, { maxBuffer: 256 * 1024 * 1024 });
    const cut = stdout.lastIndexOf('\n');
    return new Response(stdout.slice(0, cut), { status: Number(stdout.slice(cut + 1)) || 599 });
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function resolveInput(file: string): string {
  if (file.startsWith('guide:')) {
    const p = path.join(GUIDE, file.slice('guide:'.length));
    if (!fs.existsSync(p)) {
      throw new Error(`Guide fixture missing: ${p}. Fetch it first (qa/fixtures/README.md). Nothing was sent.`);
    }
    return p;
  }
  return path.isAbsolute(file) ? file : path.join(EXAMPLES, file);
}

function dataUrl(file: string): string {
  const buf = fs.readFileSync(resolveInput(file));
  const mime = file.endsWith('.png') ? 'image/png' : 'image/jpeg';
  return `data:${mime};base64,${buf.toString('base64')}`;
}

(async () => {
  const dry = process.argv.includes('--dry');
  const key = process.env.GEMINI_API_KEY;
  if (!key && !dry) throw new Error('No GEMINI_API_KEY — nothing run, nothing spent.');
  if (!dry && !process.argv.includes('--yes-spend')) throw new Error('Paid. Re-run with --yes-spend.');

  const only = (process.argv.find((a) => a.startsWith('--runs=')) ?? '').replace('--runs=', '').split(',').filter(Boolean);
  if (!dry) globalThis.fetch = curlFetch as typeof fetch;
  setGeminiConfig({ engine: 'gemini', key: key ?? 'dry-run', remember: false });
  const provider = getActiveProvider();
  if (!provider) throw new Error('No active provider after configuring the key.');

  fs.mkdirSync(OUT, { recursive: true });
  const report: unknown[] = [];
  let spent = 0;
  let planned = 0;

  const set = process.argv.includes('--owed')
    ? OWED
    : process.argv.includes('--probe')
    ? PROBE
    : process.argv.includes('--new')
    ? NEW_TOOLS
    : process.argv.includes('--skipped')
    ? SKIPPED
    : process.argv.includes('--verify')
      ? VERIFY
      : RUNS;
  for (const run of set) {
    if (only.length && !only.includes(run.id)) continue;
    const def = featureDef(run.tool);
    const settings = { ...def.defaultSettings, ...(run.settings ?? {}) } as never;
    const ctx = { refine: false };
    const prompt = def.buildPrompt(settings, {
      useMoodboard: false,
      useStyleRef: false,
      hasMarker: run.marked ?? false,
      hasImage: Boolean(run.input),
      extras: run.extra ? [true] : [],
    });
    const req = buildFeatureRequest(run.tool, settings, {
      inputImages: [run.input, run.extra]
        .filter((f): f is string => Boolean(f))
        .map((f) => (dry && run.chained && f === run.input && !fs.existsSync(f) ? PLACEHOLDER : dataUrl(f))),
      prompt,
      ctx,
    });
    if (run.options) Object.assign(req.options, run.options);

    // How many API calls this ONE request becomes. `provider.generate` expands a
    // request into per-image jobs internally, so a tool that returns a sheet of
    // six views bills six times. Counting it here — with the app's own
    // `jobsFor` — is the difference between a 15-call budget and a 40-call one.
    const jobs = jobsFor(req, prompt);
    process.stdout.write(`\n─── ${run.id} · ${run.tool}  (${jobs.length} call${jobs.length === 1 ? '' : 's'})\n    ${run.title}\n`);
    fs.writeFileSync(path.join(OUT, `run-${run.id}-prompt.txt`), jobs.map((j) => `# ${j.label}\n${j.prompt}`).join('\n\n---\n\n'));
    // The input is NOT copied here: every fixture already ships in
    // `public/examples/`, and `report.json` names the one each run used.
    if (dry) {
      planned += jobs.length;
      continue;
    }

    // Reframe & Extend: the app pads in runFeature, which this harness bypasses,
    // so the SAME canvas code runs here via qa/canvasOps.cjs (in Chromium).
    const frame = req.options.reframe;
    let place = '';
    let original = '';
    if (frame && run.input && !dry) {
      original = resolveInput(run.input);
      const padded = path.join(OUT, `run-${run.id}-padded.png`);
      place = execFileSync('node', [path.join(ROOT, 'qa', 'canvasOps.cjs'), 'pad', original, frame.ratio, frame.anchor, padded], {
        encoding: 'utf8',
      });
      req.inputImages[0] = dataUrl(padded);
    }

    try {
      const result = await provider.generate(req);
      spent += jobs.length;
      const failures = result.failures ?? [];
      for (const f of failures) console.log(`    FAILED  ${f.label} — ${f.error.slice(0, 160)}`);
      if (!result.images.length) {
        report.push({ ...run, status: 'no-image', calls: jobs.length, failures });
        continue;
      }
      // Every panel is saved, not just the first: a six-view sheet that agrees
      // with itself can only be judged from all six.
      const saved: string[] = [];
      result.images.forEach((img, i) => {
        const b64 = img.url.split(',')[1];
        const suffix = result.images.length > 1 ? `-${String(i + 1).padStart(2, '0')}` : '';
        const file = `run-${run.id}-output${suffix}.png`;
        fs.writeFileSync(path.join(OUT, file), Buffer.from(b64, 'base64'));
        saved.push(file);
        if (frame?.keepOriginal && place) {
          // Both are kept: the raw output shows what the MODEL did, the pasted one
          // what the user gets.
          const final = `run-${run.id}-final${suffix}.jpg`;
          execFileSync('node', [path.join(ROOT, 'qa', 'canvasOps.cjs'), 'paste', original, path.join(OUT, file), place, path.join(OUT, final)]);
          saved.push(final);
        }
        console.log(`    OK  ${img.label}  ${Math.round((b64.length * 0.75) / 1024)}KB  → ${file}`);
      });
      report.push({
        ...run,
        status: failures.length ? 'partial' : 'generated',
        calls: jobs.length,
        labels: result.images.map((i) => i.label),
        files: saved,
        sources: result.images.flatMap((i) => i.sources ?? []),
        searchQueries: result.images.flatMap((i) => i.searchQueries ?? []),
        failures,
      });
    } catch (err) {
      console.log(`    ERROR — ${String(err).slice(0, 200)}`);
      report.push({ ...run, status: 'error', calls: jobs.length, why: String(err).slice(0, 400) });
    }
  }

  if (dry) {
    console.log(`\n${planned} API call(s) would be billed. Nothing was sent.`);
    return;
  }
  const reportName = process.argv.includes('--owed')
    ? 'report-owed.json'
    : process.argv.includes('--probe')
    ? 'report-probe.json'
    : process.argv.includes('--new')
    ? 'report-new.json'
    : process.argv.includes('--skipped')
    ? 'report-skipped.json'
    : process.argv.includes('--verify')
      ? 'report-verify.json'
      : 'report.json';
  fs.writeFileSync(path.join(OUT, reportName), JSON.stringify({ runs: report, generations: spent }, null, 2));
  console.log(`\n${spent} generation(s) attempted. Results in qa/live-results/`);
})();
